### ISSUE TITLE
[Feature] Multiple Stores

### ISSUE THREAD

**Issue by KivaGale** [Julexar/itemstore#1]
One problem I have is having multiple stores.

**Describe the feature you'd like**
I would like the ability to have more than one store, 

Example:

!ms_inventory Wands_Staffs_and_Capes
!ms_inventory Mystic_Marvels

Both pulling up different stores.

Another helpful thing with this would be a command to list all stores.

**Comment by Julexar** [comment]
Thanks for your Feedback. I will see what I can do

**Comment by Julexar** [comment]
This is gonna take a while as I'm gonna have to rewrite the entire script

**Comment by Julexar** [comment]
- [x] Rewrite script
- [x] Ensure usability
- [x] Test Stores
- [ ] Fix Handouts

**Comment by Julexar** [comment]
Have the first draft done, working on further improving and making it work

**Comment by Julexar** [comment]
@KivaGale Sadly I will need to put this on hold as there are some problems. So for now I won't continue working on this until I find a way to implement your wish

**Comment by Julexar** [comment]
Alright @KivaGale , good news: I think I may have found a way to make multiple stores work. I will begin working on it now and I'll let you know once I've added it.

**Comment by Julexar** [comment]
@KivaGale I'm very close to finishing the new Version, look forward to my next release ^^

**Comment by KivaGale** [comment]
Oooo hype!
